import bpy
from bpy.props import BoolProperty, EnumProperty, FloatVectorProperty
from ..base import SuperLuxCoreNodeMaterial
from .glass import THIN_FILM_DESCRIPTION
from ... import utils
from ...utils import node as utils_node
from ...utils.node import ThinFilmCoating, SellmeierDispersion


# Measured-media subsurface presets. Mirrors the engine-side
# "subsurfacepreset" table - generated by
# SuperLuxCore/dev-tools/gen_sss_presets.py from measured sigma_a/
# sigma_s' (Jensen et al. SIGGRAPH'01). Picking a preset seeds the
# subsurface sockets below; all of them stay editable afterwards.
#   (subsurface albedo RGB, radius RGB scale, scale in scene units)
SSS_PRESETS = {
    "skin_dark":  ((0.4683, 0.2887, 0.1914), (1.0, 0.7352, 0.5181), 0.00130),
    "skin_light": ((0.6322, 0.4661, 0.3901), (1.0, 0.6645, 0.5700), 0.00091),
    "chicken":    ((0.3648, 0.2185, 0.1862), (1.0, 0.5749, 0.2895), 0.00606),
    "apple":      ((0.8549, 0.8495, 0.5640), (0.8792, 0.8423, 1.0000), 0.00050),
    "potato":     ((0.7786, 0.6399, 0.2793), (0.9818, 0.9450, 1.0000), 0.00149),
    "marble":     ((0.8456, 0.8099, 0.7750), (1.0, 0.8354, 0.7290), 0.00046),
    "cream":      ((0.9769, 0.9052, 0.7421), (0.4290, 0.5786, 1.0000), 0.00032),
    "whole_milk": ((0.9124, 0.8872, 0.7740), (1.0, 0.7941, 0.6742), 0.00039),
    "skim_milk":  ((0.8255, 0.8237, 0.7032), (1.0, 0.5737, 0.3664), 0.00143),
    "ketchup":    ((0.2293, 0.0126, 0.0037), (1.0, 0.2317, 0.1628), 0.00415),
}

SSS_PRESET_ITEMS = [
    ("custom", "Custom", "Manual subsurface parameters", 0),
    ("skin_light", "Skin (Light)",
     "Measured fair skin (Jensen'01 Skin2) - use specular IOR ~1.4", 1),
    ("skin_dark", "Skin (Dark)",
     "Measured dark skin (Jensen'01 Skin1) - use specular IOR ~1.4", 2),
    ("marble", "Marble", "Measured marble (Jensen'01) - use specular IOR ~1.5", 3),
    ("cream", "Cream", "Measured cream (Jensen'01) - use specular IOR ~1.35", 4),
    ("whole_milk", "Whole Milk", "Measured whole milk (Jensen'01) - IOR ~1.35", 5),
    ("skim_milk", "Skim Milk", "Measured skim milk (Jensen'01) - IOR ~1.35", 6),
    ("ketchup", "Ketchup", "Measured ketchup (Jensen'01) - IOR ~1.35", 7),
    ("apple", "Apple", "Measured apple flesh (Jensen'01) - IOR ~1.35", 8),
    ("potato", "Potato", "Measured potato (Jensen'01) - IOR ~1.35", 9),
    ("chicken", "Chicken", "Measured chicken tissue (Jensen'01 Chicken1) - IOR ~1.4", 10),
]


class SuperLuxCoreNodeMatOpenPBR(SuperLuxCoreNodeMaterial, bpy.types.Node):
    """ASWF OpenPBR Surface v1.1 material.

    Lobe stack (top to bottom): fuzz -> coat -> specular/diffuse/metal ->
    transmission/subsurface. Matches the parameterization of Blender's
    Principled BSDF so assets transfer directly.
    """
    bl_label = "OpenPBR Material"
    bl_width_default = 210

    def _set_enabled(self, names, enabled):
        # Blender 5.2: disabled sockets are excluded from inputs[name]
        # key lookups, so address them by index via find().
        for name in names:
            self.inputs[self.inputs.find(name)].enabled = enabled

    def update_use_thinfilmcoating(self, context):
        self._set_enabled(("Film Weight",), self.use_thinfilmcoating)
        ThinFilmCoating.toggle(self, context)

    def _migrate_sss_sockets(self):
        # Pre-rename files stored the scalar in "Subsurface Radius" and
        # the RGB scale in "Subsurface Radius Scale" (OpenPBR spec order).
        # Migrate the scalar first so its old name frees up for the RGB
        # socket; new-name lookups then hit the right sockets.
        i = self.inputs.find("Subsurface Radius")
        if i >= 0 and self.inputs[i].bl_idname == "SuperLuxCoreSocketFloatPositive":
            self.inputs[i].name = "Subsurface Scale"
        i = self.inputs.find("Subsurface Radius Scale")
        if i >= 0:
            self.inputs[i].name = "Subsurface Radius"

    def update_use_subsurface(self, context):
        self._migrate_sss_sockets()
        self._set_enabled(("Subsurface Weight", "Subsurface Color",
                           "Subsurface Radius", "Subsurface Scale",
                           "Subsurface Anisotropy"), self.use_subsurface)

    def update_sss_preset(self, context):
        preset = SSS_PRESETS.get(self.sss_preset)
        if preset:
            albedo, radius, scale = preset
            for name, value in (("Subsurface Color", albedo),
                                ("Subsurface Radius", radius),
                                ("Subsurface Scale", scale),
                                ("Subsurface Weight", 1.0),
                                ("Subsurface Anisotropy", 0.0)):
                i = self.inputs.find(name)
                if i >= 0 and not self.inputs[i].is_linked:
                    self.inputs[i].default_value = value
        utils_node.force_viewport_update(self, context)

    def update_use_transmission(self, context):
        self._set_enabled(("Transmission Weight", "Transmission Color",
                           "Transmission Depth", "Transmission Scatter",
                           "Transmission Scatter Anisotropy", "Dispersion"),
                          self.use_transmission)

    def update_use_coat(self, context):
        self._set_enabled(("Coat Weight", "Coat Color", "Coat Roughness",
                           "Coat Anisotropy", "Coat Rotation", "Coat IOR",
                           "Coat Darkening"), self.use_coat)

    def update_use_fuzz(self, context):
        self._set_enabled(("Fuzz Weight", "Fuzz Color", "Fuzz Roughness"),
                          self.use_fuzz)

    use_thinfilmcoating: BoolProperty(name="Thin Film Coating", default=False,
                                      description=THIN_FILM_DESCRIPTION,
                                      update=update_use_thinfilmcoating)
    use_subsurface: BoolProperty(name="Subsurface", default=False,
                                 description="Enable the subsurface scattering lobe "
                                             "(implicit interior volume from radius/color). "
                                             "Pick a Subsurface Preset for measured media",
                                 update=update_use_subsurface)
    sss_preset: EnumProperty(name="Subsurface Preset",
                             items=SSS_PRESET_ITEMS, default="custom",
                             description="Measured-medium preset: seeds Subsurface "
                                         "Color/Radius/Scale with measured values "
                                         "(kept editable; set to Custom to keep them)",
                             update=update_sss_preset)
    use_transmission: BoolProperty(name="Transmission", default=False,
                                   description="Enable the specular transmission lobe",
                                   update=update_use_transmission)
    use_coat: BoolProperty(name="Coat", default=False,
                           description="Enable the dielectric clear-coat lobe",
                           update=update_use_coat)
    use_fuzz: BoolProperty(name="Fuzz", default=False,
                           description="Enable the retro-reflective fuzz (sheen) lobe",
                           update=update_use_fuzz)

    dispersion_model: EnumProperty(name="Dispersion Model",
                                   items=SellmeierDispersion.MODEL_ITEMS,
                                   default="cauchy",
                                   update=utils_node.force_viewport_update)
    sellmeier_preset: EnumProperty(name="Glass Preset",
                                   items=SellmeierDispersion.PRESET_ITEMS,
                                   default="N-BK7",
                                   update=utils_node.force_viewport_update)
    sellmeier_b: FloatVectorProperty(name="Sellmeier B", size=3,
                                     default=(1.0, 0.5, 1.0),
                                     description="Sellmeier B1 B2 B3 coefficients",
                                     update=utils_node.force_viewport_update)
    sellmeier_c: FloatVectorProperty(name="Sellmeier C", size=3,
                                     default=(0.006, 0.02, 100.0),
                                     description="Sellmeier C1 C2 C3 coefficients (um^2)",
                                     update=utils_node.force_viewport_update)

    def init(self, context):
        # Base
        self.add_input("SuperLuxCoreSocketColor", "Base Color", [0.8] * 3)
        self.add_input("SuperLuxCoreSocketFloat0to1", "Base Weight", 1)
        self.add_input("SuperLuxCoreSocketFloat0to1", "Base Metalness", 0)
        self.add_input("SuperLuxCoreSocketFloat0to1", "Diffuse Roughness", 0)
        # Specular
        self.add_input("SuperLuxCoreSocketFloat0to1", "Specular Weight", 1)
        self.add_input("SuperLuxCoreSocketColor", "Specular Color", [1.0] * 3)
        self.add_input("SuperLuxCoreSocketFloat0to1", "Specular Roughness", 0.3)
        self.add_input("SuperLuxCoreSocketFloat0to1", "Specular Anisotropy", 0)
        self.add_input("SuperLuxCoreSocketFloat0to1", "Specular Rotation", 0)
        self.add_input("SuperLuxCoreSocketIOR", "Specular IOR", 1.5)
        # Transmission
        self.add_input("SuperLuxCoreSocketFloat0to1", "Transmission Weight", 0, enabled=False)
        self.add_input("SuperLuxCoreSocketColor", "Transmission Color", [1.0] * 3, enabled=False)
        self.add_input("SuperLuxCoreSocketFloatPositive", "Transmission Depth", 0, enabled=False)
        self.add_input("SuperLuxCoreSocketColor", "Transmission Scatter", [0.0] * 3, enabled=False)
        self.add_input("SuperLuxCoreSocketFloatUnbounded", "Transmission Scatter Anisotropy", 0, enabled=False)
        self.add_input("SuperLuxCoreSocketFloat0to1", "Dispersion", 0, enabled=False)
        # Subsurface (Principled-style naming: Radius = per-channel
        # relative mfp, Scale = absolute mfp in scene units)
        self.add_input("SuperLuxCoreSocketFloat0to1", "Subsurface Weight", 0, enabled=False)
        self.add_input("SuperLuxCoreSocketColor", "Subsurface Color", [1.0] * 3, enabled=False)
        self.add_input("SuperLuxCoreSocketColor", "Subsurface Radius",
                       [1.0, 0.2, 0.1], enabled=False)
        self.add_input("SuperLuxCoreSocketFloatPositive", "Subsurface Scale",
                       0.01, enabled=False)
        self.add_input("SuperLuxCoreSocketFloatUnbounded", "Subsurface Anisotropy", 0, enabled=False)
        # Coat
        self.add_input("SuperLuxCoreSocketFloat0to1", "Coat Weight", 0, enabled=False)
        self.add_input("SuperLuxCoreSocketColor", "Coat Color", [1.0] * 3, enabled=False)
        self.add_input("SuperLuxCoreSocketFloat0to1", "Coat Roughness", 0, enabled=False)
        self.add_input("SuperLuxCoreSocketFloat0to1", "Coat Anisotropy", 0, enabled=False)
        self.add_input("SuperLuxCoreSocketFloat0to1", "Coat Rotation", 0, enabled=False)
        self.add_input("SuperLuxCoreSocketIOR", "Coat IOR", 1.5, enabled=False)
        self.add_input("SuperLuxCoreSocketFloat0to1", "Coat Darkening", 1, enabled=False)
        # Fuzz
        self.add_input("SuperLuxCoreSocketFloat0to1", "Fuzz Weight", 0, enabled=False)
        self.add_input("SuperLuxCoreSocketColor", "Fuzz Color", [1.0] * 3, enabled=False)
        self.add_input("SuperLuxCoreSocketFloat0to1", "Fuzz Roughness", 0.5, enabled=False)
        # Thin film
        self.add_input("SuperLuxCoreSocketFloat0to1", "Film Weight", 1, enabled=False)
        ThinFilmCoating.init(self)
        self.add_common_inputs()

        self.outputs.new("SuperLuxCoreSocketMaterial", "Material")

    def draw_buttons(self, context, layout):
        col = layout.column(align=True)
        col.prop(self, "use_transmission")
        col.prop(self, "use_subsurface")
        if self.use_subsurface:
            col.prop(self, "sss_preset")
        col.prop(self, "use_coat")
        col.prop(self, "use_fuzz")
        col.prop(self, "use_thinfilmcoating")
        if self.use_transmission:
            SellmeierDispersion.draw(self, layout)

    def sub_export(self, exporter, depsgraph, props, superluxcore_name=None, output_socket=None):
        exp = lambda n: self.inputs[n].export(exporter, depsgraph, props)
        definitions = {
            "type": "openpbr",
            "basecolor": exp("Base Color"),
            "baseweight": exp("Base Weight"),
            "basemetalness": exp("Base Metalness"),
            "basediffuseroughness": exp("Diffuse Roughness"),
            "specularweight": exp("Specular Weight"),
            "specularcolor": exp("Specular Color"),
            "specularroughness": exp("Specular Roughness"),
            "specularanisotropy": exp("Specular Anisotropy"),
            "specularrotation": exp("Specular Rotation"),
            "specularior": exp("Specular IOR"),
        }

        if self.use_transmission:
            definitions["transmissionweight"] = exp("Transmission Weight")
            definitions["transmissioncolor"] = exp("Transmission Color")
            definitions["transmissiondepth"] = exp("Transmission Depth")
            definitions["transmissionscatter"] = exp("Transmission Scatter")
            definitions["transmissionscatteranisotropy"] = exp("Transmission Scatter Anisotropy")
            # Sellmeier replaces the Cauchy-B "dispersion" property
            if not SellmeierDispersion.export(self, definitions):
                definitions["dispersion"] = exp("Dispersion")

        if self.use_subsurface:
            self._migrate_sss_sockets()
            # UI is Principled-style: "Subsurface Radius" is the RGB
            # scale vector, "Subsurface Scale" the scalar (SDL keeps the
            # OpenPBR spec names: radius=scalar, radiusscale=vector)
            definitions["subsurfaceweight"] = exp("Subsurface Weight")
            definitions["subsurfacecolor"] = exp("Subsurface Color")
            definitions["subsurfaceradiusscale"] = exp("Subsurface Radius")
            definitions["subsurfaceradius"] = exp("Subsurface Scale")
            definitions["subsurfaceanisotropy"] = exp("Subsurface Anisotropy")
            if self.sss_preset != "custom":
                definitions["subsurfacepreset"] = self.sss_preset

        if self.use_coat:
            definitions["coatweight"] = exp("Coat Weight")
            definitions["coatcolor"] = exp("Coat Color")
            definitions["coatroughness"] = exp("Coat Roughness")
            definitions["coatanisotropy"] = exp("Coat Anisotropy")
            definitions["coatrotation"] = exp("Coat Rotation")
            definitions["coatior"] = exp("Coat IOR")
            definitions["coatdarkening"] = exp("Coat Darkening")

        if self.use_fuzz:
            definitions["fuzzweight"] = exp("Fuzz Weight")
            definitions["fuzzcolor"] = exp("Fuzz Color")
            definitions["fuzzroughness"] = exp("Fuzz Roughness")

        if self.use_thinfilmcoating:
            weight_socket = self.inputs["Film Weight"]
            weight = weight_socket.export(exporter, depsgraph, props)
            thickness_socket = self.inputs[ThinFilmCoating.THICKNESS_NAME]
            thickness = thickness_socket.export(exporter, depsgraph, props)
            if (weight_socket.is_linked or weight > 0) and \
                    (thickness_socket.is_linked or thickness > 0):
                definitions["filmweight"] = weight
                # The socket is in nm (artist convention, same as the Disney
                # node); the SuperLuxCore OpenPBR property is in micrometers.
                if isinstance(thickness, str):
                    tex_name = utils.sanitize_superluxcore_name(superluxcore_name + "_film_nm_to_um")
                    props.Set(utils.luxutils.create_props("scene.textures." + tex_name + ".", {
                        "type": "scale",
                        "texture1": thickness,
                        "texture2": 0.001,
                    }))
                    thickness = tex_name
                else:
                    thickness *= 0.001
                definitions["filmthickness"] = thickness
                definitions["filmior"] = self.inputs[ThinFilmCoating.IOR_NAME].export(
                        exporter, depsgraph, props)

        self.export_common_inputs(exporter, depsgraph, props, definitions)
        return self.create_props(props, definitions, superluxcore_name)
